### ISSUE TITLE
Add checksums for smith packets

### ISSUE THREAD

**Issue by indutny** [c9/smith#9]
When receiving incorrect data smith will try to allocate buffer using wrong packet headers. This may lead to sudden V8 crashes, because allocation of 1gb memory is not really friendly way of detecting broken packets.

**Comment by zefhemel** [comment]
To put this into context, we were crashing continuously this morning due to this problem. Instead of a packet size, followed by msgpacked data. We got the string "Invalid context" back, which was interpreted as a packet size of >1GB, which crashed node.

**Comment by fjakobs** [comment]
an alternative would be to add a handshake to the transport so we are sure only smith packages are send afterwards

**Comment by creationix** [comment]
I published smith 0.1.15 that includes Fedor's checksum code.  Please
update your dependencies.

**Comment by indutny** [comment]
Closing?

**Comment by creationix** [comment]
For some reason I thought it was already closed, but I now see that was only the attached pull request that was closed.
